

apiVersion: v1
kind: Service
metadata:

  name: zipkin
  labels:
    app: zipkin
spec:
  type: NodePort
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 9411
  selector:
    app: zipkin