apiVersion: apps/v1
kind: StatefulSet
metadata:

  name: registry-ui
  labels:
    app: registry-ui
spec:
  serviceName: registry-ui
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: hyper/docker-registry-web
          resources:
            limits:
              cpu: 400m
              memory: 768Mi
            requests:
              cpu: 400m
              memory: 768Mi
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Asia/Shanghai
#            - name: REGISTRY_URL
#              value: http://registry-0.registry.default.svc.cluster.local:5000/v2
#            - name: REGISTRY_NAME
#              value: http://192.168.0.254:5000
#            - name: REGISTRY_READONLY
#              value: "false"
#            - name: REGISTRY_STORAGE_DELETE_ENABLED
#              value: "true"
          volumeMounts:
            - name: vol-conf
              mountPath: /conf/config.yml
      volumes:
        - name: vol-conf
          hostPath:
            path: /www/k8s/foxdev/registry-docker/ui-conf/config.yml
            type: File