apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq
  labels:
    app: rocketmq
#  namespace: default
spec:
  serviceName: rocketmq
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  template:
    metadata:
      labels:
        app: rocketmq
    spec:
      containers:
        - name: rocketmq
          image: foxiswho/rocketmq:server
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 450m
              memory: 2000Mi
            requests:
              cpu: 400m
              memory: 2000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT
              value: -Duser.home=/opt
            - name: JAVA_OPT_EXT
              value: -server -Xms2000m -Xmx2000m -Xmn256m
          ports:
            - containerPort: 9876
          volumeMounts:
            - name: vol-logs
              mountPath: /opt/logs
            - name: vol-init-d
              mountPath: /opt/store
      volumes:
        - name: vol-logs
          hostPath:
            path: /www/k8s/foxdev/rocketmq/logs
            type: Directory
        - name: vol-init-d
          hostPath:
            path: /www/k8s/foxdev/rocketmq/store
            type: Directory