apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
  labels:
    name: mariadb
#  namespace: default
spec:
  replicas: 1
  selector:
    name: mariadb
  template:
    metadata:
      labels:
        name: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 768Mi
            requests:
              cpu: 200m
              memory: 512Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: vol-data
              mountPath: /var/lib/mysql
            - name: vol-conf
              mountPath: /etc/mysql/mariadb.conf.d
      volumes:
        - name: vol-data
          hostPath:
            path: /www/k8s/foxdev/mariadb/data
            type: Directory
        - name: vol-data
          hostPath:
              path: /www/k8s/foxdev/mariadb/mariadb.conf.d
              type: Directory