

apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: sentinel
  labels:
    name: sentinel
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8700
      nodePort: 8700
  selector:
    name: sentinel